### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ksolomon** [TheNightmanCodeth/open-in-code#1]
I tried to install it this morning (on Firefox 105.0.1), but even with the signature check turned off, FF says it can't be installed.  I've restarted FF multiple times, even restarted my computer, still no joy.

**Comment by TheNightmanCodeth** [comment]
[It's been accepted to FF addons!](https://addons.mozilla.org/en-US/firefox/addon/open-in-visual-studio-code/) Make sure you re-enable the signature check in your FF (if you want) and install from there!
